name: premerge-validation-test

on:
  pull_request:
    branches: [deploy]
    types: [opened, synchronize, reopened, labeled]

jobs:
  premerge-validate:
    runs-on: ubuntu-latest #running on Github runners
    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up JDK 1.8 #to setup Java for building packager
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Cloud SDK #to use gsutil commands when searching for necessary files
      uses: google-github-actions/setup-gcloud@v0

    - name: Build packager #create packages.json file
      run : python3 ./.github/scripts/premerge-build.py

    - name: Get list of changed files #external action to get list of added, modified, renamed files within pull request
      uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
      if: always()
      id: list
      with:
        format: 'json'

    - name: Log list and search for necessary files #list out , find and search for missing artifacts
      if: always()
      env:
        ADDED_LIST: ${{ steps.list.outputs.added }}
        MODIFIED_LIST: ${{ steps.list.outputs.modified }}
      run: python3 ./.github/scripts/premerge-validate.py